### ISSUE TITLE
Amount(value: Double) false positive tooManyFractionalDigits

### ISSUE THREAD

**Issue by LukasKorba** [pacu/zcash-swift-payment-uri#60]
### The Bug
When I try to construct Amount with a double initializer it fails for most fractions except first one. 0.1 is fine while 0.0xxx fails. The problem is it converts to BigDecimal and that one has 12 fractional digits. So 0.02 is represented as 0.020000000000. max(-exponent, 0) function then returns 12 and comparison to 8 max for Zatoshi fails the code.

### Expected result
Any double with up to 8 fractional digits must pass Amount(value: Double) initializer. I see other initializers use .trim which is supposed to trimp the zeroes. It's not applied to double path though.

**Comment by pacu** [comment]
Thanks for reporting this. I'll check it out
